# Generated by Django 5.1 on 2024-08-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Описание элемента', max_length=200),
        ),
    ]
